@url = http://localhost:5000/conferences-module
@hostId = d1339dfb-c218-46f2-bcf1-520f6badfdd2
@conferenceId = 1b0d20c8-2a3e-4467-b222-e3543d99e599

###
GET {{url}}

###
POST {{url}}/hosts
content-Type: application/json

{
    "name": "Host #1",
    "description": "Lorem ipsum"
}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
content-Type: application/json

{
    "name": "Host #2"
}

###
DELETE {{url}}/hosts/{{hostId}}

###
POST {{url}}/conferences
content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "Conference #1",
    "description": "Lorem ipsum",
    "location": "Test 123",
    "from": "2021-05-01",
    "to": "2021-05-02",
    "participantsLimit": 100,
    "logoUrl": null
}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
PUT {{url}}/conferences/{{conferenceId}}
content-Type: application/json

{
    "name": "Conference #2",
    "description": "Lorem ipsum",
    "location": "Test 123",
    "from": "2021-05-01",
    "to": "2021-05-02",
    "participantsLimit": 100,
    "logoUrl": null
}

###
DELETE {{url}}/conferences/{{conferenceId}}